### ISSUE TITLE
[FR] Headerless CSV

### ISSUE THREAD

**Issue by thareh** [bmx-ng/text.mod#11]
Hey,

I can't really make out if ZSV supports this or not, but it would be swell with the ability to use the CSV parser without a header so the columns are simply called 0, 1, 2 etc instead.

Thanks!

**Comment by woollybah** [comment]
I believe it must have a header - which is why it has the option to add your own if you are dealing with files without headers.
Now, whether you want to be able to access the columns by index instead, is possibly a different problem that could be resolved by the module?

**Comment by thareh** [comment]
I found a solution by adding my own header and then accessing the columns by their index. But it would be nice with a built-in option for this, but I guess that's an issue for ZSV? :)
