### ISSUE TITLE
[PDF.mod] include file hpdf.h not found

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/text.mod#15]
Compiling an example here (on Linux) leads to:
```
In file included from /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/text.mod/pdf.mod/glue.c:20:
/home/ronny/Arbeit/Tools/BlitzMaxNG/mod/text.mod/pdf.mod/libharu/include/hpdf.h:20:10: fatal error: hpdf_config.h: Datei oder Verzeichnis nicht gefunden
   20 | #include "hpdf_config.h"
      |          ^~~~~~~~~~~~~~~
```

(it is only provided for Win32)

**Comment by GWRon** [comment]
To enable this module: `sudo apt-get install libhpdf-dev`

Dunno if that information (the libhpdf-dev requirement) should be mentioned somewhere - maybe in an "intro.bbdoc" or so (or in the source too ?)

**Comment by woollybah** [comment]
It works with the latest version.

**Comment by GWRon** [comment]
Yes - once you installed "libhpdf-dev". Need to check if it works on Windows as midimaster wrote on Syntaxbomb:
> I also had a look on the text-module, escpecially the PDF-part. but there is no Explanation or deep manual/ reference book. Also the examples crashed.

Will try them out now

**Comment by woollybah** [comment]
What libhpdf-dev dependency?

**Comment by GWRon** [comment]
the one I mentioned in the initial post:
If you try to use text.pdf on a default Ubuntu 22.04 based Mint XFCE it won't find the file:
```
In file included from /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/text.mod/pdf.mod/glue.c:20:
/home/ronny/Arbeit/Tools/BlitzMaxNG/mod/text.mod/pdf.mod/libharu/include/hpdf.h:20:10: fatal error: hpdf_config.h: Datei oder Verzeichnis nicht gefunden
   20 | #include "hpdf_config.h"
      |          ^~~~~~~~~~~~~~~
```

Installed the dev-library of libhpdf and it compiled.

**Comment by woollybah** [comment]
Isn't there one in the include dir?

**Comment by GWRon** [comment]
it does not find the linux one ... but after I run "sudo updatedb" + "locate hpdf_config.h" I received this:
![image](https://user-images.githubusercontent.com/2625226/232587550-ef4d8ede-5f0c-42d4-81b2-7b746f814101.png)

Searchmonkey still does not find the files in that folder ... 

and now checking manually with the file manager I see that this file seems to be created by something ... (check the file's timestamp)

![image](https://user-images.githubusercontent.com/2625226/232587935-420d7a08-7670-40d9-af30-844b8ccf3d59.png)

**Comment by woollybah** [comment]
https://github.com/bmx-ng/text.mod/commit/ffd5072a64986276c18a05f993bfa42a872a5e29

**Comment by woollybah** [comment]
The first line of your search shows the file is there.

Is that not working for you for some reason?

**Comment by GWRon** [comment]
Yeah I know:
![image](https://user-images.githubusercontent.com/2625226/232588149-5e310c70-995f-42f8-a815-183700bcb325.png)

Maybe my file system has an hickup? Experienced some random "delays" since this _fresh_ install of the latest Mint.


> Is that not working for you for some reason?

Now it is working (but I also have had installed that dev-lib)

And yes, "ls" finds the file - but searchmonkey not -- which is like a "discrepancy"

![image](https://user-images.githubusercontent.com/2625226/232588501-944938bd-8710-4651-a196-2296b171ad67.png)

**Comment by woollybah** [comment]
I don't have that library installed, and I was able to install the module, build and run the arc example.

**Comment by woollybah** [comment]
I'll have a look at adding some "deep" manual next... but the examples are quite self-explanatory.
