### ISSUE TITLE
CSV header issue

### ISSUE THREAD

**Issue by thareh** [bmx-ng/text.mod#6]
Hello,

**TCsvHeader.Put()** does not resize the field **cols** before inserting into it. (csv.bmx:285)

Perhaps change to something like this?
```
Method Put(col:String, index:Int)
	If cols.length < index+1
		cols = cols[..index+1]
	EndIf
	cols[index] = col
	map.Insert(col, New TInt(index))
End Method
```

Cheers!

**Comment by woollybah** [comment]
It shouldn't need to. It should already be large enough when the header instance is created?

**Comment by woollybah** [comment]
The bug is in ReadHeader() :)
Thanks.
