### ISSUE TITLE
[csv.mod] Last column empty issue

### ISSUE THREAD

**Issue by thareh** [bmx-ng/text.mod#7]
Hey,

Using the following CSV-data:
```
foo;bar
1;
```

Should in my world produce a row with 2 columns foo=1 and bar=NULL, but that does not seem to be the case - is this an issue with ZSV?

Thanks!

**Comment by woollybah** [comment]
Interesting, what results do you get?

**Comment by woollybah** [comment]
Did you remember to set the options delimiter to `;` ? - the default is comma.

**Comment by thareh** [comment]
The result I get is only 1 column, and yes I did set the delimiter correctly - adding any kind of text to the second column and it works as expected.

Thanks!

**Comment by woollybah** [comment]
Ah, I see.
Does the file end at the end of the second line? (i.e. there's no new-line?)

**Comment by thareh** [comment]
Ah yes it does, but the data provided is for demonstration purposes. In the real world data where I stumbled upon this issue the row ends with a line ending and not EOF.

I can dig a bit deeper tomorrow and get back with something more.

Thanks!

**Comment by woollybah** [comment]
I can make it always return "at least" header.ColumnCount(), if that will help.

**Comment by woollybah** [comment]
Anyway, you can always ask for the value for column "bar". It will simply return Null if there isn't a column for that row.

**Comment by GWRon** [comment]
Each `TCsvCol` has `Method ColumnCount:Int()` - which should equal to the actually set amount of "filled columns". Columns missing should be seen as nan/null.
I would not expect the CSV-module to "fill in" information which the original file did _not_ contain.


Maybe @thareh should provide an "complete" example and what he expects bmx/the module to spit out.

**Comment by GWRon** [comment]
Change line-endings of full.csv to "CR/LF" (Windows-style) and you wont see the message. Keep it at the used "LF" (Unix-style) and the message is there.

**Comment by GWRon** [comment]
playing a bit with "full.csv" (removing single characters in entries until it suddenly "works") shows that it is not a specific char bugging out handling.

- I removed chars from a specific line's first string entry (empty `""`)
- then I removed chars from the category string element in that line until it did not spit out the warning
- removing 3 more of the category string kept it running
- adding back 3 chars to the first string entry (the article name) and it still worked
- adding back another char to the first string - and it bugs out

This sounds to me as if the "line length" is somehow an issue.

**Comment by GWRon** [comment]
Changing the CSV-File from "UTF-8" to "UTF-7" makes it run when it normally would spit out the warning. So maybe it stumbles over the utf8-encoding and assumes wrong string lengths?

**Comment by thareh** [comment]
Thank you for your thorough investigation @GWRon!

I tried changing the line-endings to CR/LF and it did get past the previous error, but later in the file the same thing happens. (I truncated the full.csv file you have for comfort)

How did you go about to convert to UTF-7? I'd like to try it out myself.

Thanks!

**Comment by GWRon** [comment]
I simply changed it after opening it in Geany (the texteditor I use in my Linux Mint xfce).

Yet I think this might all be a red herring. Just stuff leading to a faulty piece of code to fail - without properly indicating which piece of code it is.
